<img src="https://upload.wikimedia.org/wikipedia/commons/thumb/5/58/Uber_logo_2018.svg/1024px-Uber_logo_2018.svg.png" alt="UBER LOGO" width="50%" />

# UBER Pickups

# import libraries

In [1]:
import pandas as pd
import plotly.express as px
import os

# Read data

In [2]:
location = pd.read_csv('data/taxi-zone-lookup.csv')
print('Lines / Columns : ', location.shape)

Lines / Columns :  (265, 3)

In [3]:
files = ["data/uber-raw-data-apr14.csv", "data/uber-raw-data-may14.csv", "data/uber-raw-data-jun14.csv", 'data/uber-raw-data-jul14.csv', 'data/uber-raw-data-aug14.csv', 'data/uber-raw-data-sep14.csv']

raw_2014 = pd.concat([pd.read_csv(f) for f in files], ignore_index=True)
print('Lines / Columns : ', raw_2014.shape)

Lines / Columns :  (4534327, 4)

In [4]:
raw_2015 = pd.read_csv('data/uber-raw-data-janjune-15.csv')
print('Lines / Columns : ', raw_2015.shape)

Lines / Columns :  (14270479, 4)

# Explore dataset

In [5]:
dataframes = [location, raw_2014, raw_2015]
[print(f"Display of dataset: {display(df.head())}") for df in dataframes]

   LocationID        Borough                     Zone
0           1            EWR           Newark Airport
1           2         Queens              Jamaica Bay
2           3          Bronx  Allerton/Pelham Gardens
3           4      Manhattan            Alphabet City
4           5  Staten Island            Arden Heights

Display of dataset: None

          Date/Time      Lat      Lon    Base
0  4/1/2014 0:11:00  40.7690 -73.9549  B02512
1  4/1/2014 0:17:00  40.7267 -74.0345  B02512
2  4/1/2014 0:21:00  40.7316 -73.9873  B02512
3  4/1/2014 0:28:00  40.7588 -73.9776  B02512
4  4/1/2014 0:33:00  40.7594 -73.9722  B02512

Display of dataset: None

  Dispatching_base_num          Pickup_date Affiliated_base_num  locationID
0               B02617  2015-05-17 09:47:00              B02617         141
1               B02617  2015-05-17 09:47:00              B02617          65
2               B02617  2015-05-17 09:47:00              B02617         100
3               B02617  2015-05-17 09:47:00              B02774          80
4               B02617  2015-05-17 09:47:00              B02617          90

Display of dataset: None

[None, None, None]

We observe :
- date time MM/DD/YYYY
- lowercase and uppercase
- sorted raw data

In [6]:
# Basic stats
dataframes = {'location':location, 'raw_2014':raw_2014, 'raw_2015':raw_2015}

for name, df in dataframes.items():
    print()
    print('-------------------Dataframe : ', name, '-------------------')
    print(f"Rows :  \t {df.shape[0]}")
    print(f"Columns : \t {df.shape[1]}")

    print()
    print("Basics statistics: ")
    df_desc = df.describe(include='all') # numeric variables and catégorielles
    display(df_desc)

    print("Percentage of missing values")
    df_missing_values = df.isnull().sum()/df.shape[0]*100
    print(f"{name} : \n{df_missing_values}")
print('Done...')

-------------------Dataframe :  location -------------------
Rows :  	 265
Columns : 	 3

Basics statistics:

        LocationID Borough                                           Zone
count   265.000000     265                                            265
unique         NaN       7                                            261
top            NaN  Queens  Governor's Island/Ellis Island/Liberty Island
freq           NaN      69                                              3
mean    133.000000     NaN                                            NaN
std      76.643112     NaN                                            NaN
min       1.000000     NaN                                            NaN
25%      67.000000     NaN                                            NaN
50%     133.000000     NaN                                            NaN
75%     199.000000     NaN                                            NaN
max     265.000000     NaN                                            NaN

Percentage of missing values
location :
LocationID    0.0
Borough       0.0
Zone          0.0
dtype: float64

-------------------Dataframe :  raw_2014 -------------------
Rows :  	 4534327
Columns : 	 4

Basics statistics:

                Date/Time           Lat           Lon     Base
count             4534327  4.534327e+06  4.534327e+06  4534327
unique             260093           NaN           NaN        5
top     4/7/2014 20:21:00           NaN           NaN   B02617
freq                   97           NaN           NaN  1458853
mean                  NaN  4.073926e+01 -7.397302e+01      NaN
std                   NaN  3.994991e-02  5.726670e-02      NaN
min                   NaN  3.965690e+01 -7.492900e+01      NaN
25%                   NaN  4.072110e+01 -7.399650e+01      NaN
50%                   NaN  4.074220e+01 -7.398340e+01      NaN
75%                   NaN  4.076100e+01 -7.396530e+01      NaN
max                   NaN  4.211660e+01 -7.206660e+01      NaN

Percentage of missing values
raw_2014 :
Date/Time    0.0
Lat          0.0
Lon          0.0
Base         0.0
dtype: float64

-------------------Dataframe :  raw_2015 -------------------
Rows :  	 14270479
Columns : 	 4

Basics statistics:

,Dispatching_base_num,Pickup_date,Affiliated_base_num,locationID
count,14270479,14270479,14108284,1.427048e+07
unique,8,2744783,284,NaN
top,B02764,2015-06-27 20:52:00,B02764,NaN
freq,5753653,213,4352321,NaN
mean,NaN,NaN,NaN,1.520574e+02
std,NaN,NaN,NaN,7.159620e+01
min,NaN,NaN,NaN,1.000000e+00
25%,NaN,NaN,NaN,9.200000e+01
50%,NaN,NaN,NaN,1.570000e+02
75%,NaN,NaN,NaN,2.300000e+02
max,NaN,NaN,NaN,2.650000e+02

Percentage of missing values
raw_2015 :
Dispatching_base_num    0.000000
Pickup_date             0.000000
Affiliated_base_num     1.136577
locationID              0.000000
dtype: float64
Done...

In [7]:
# Lowercase dataframes
for name, df in dataframes.items():
    df.columns = df.columns.str.lower() # lowercase columns names
    for col in df.select_dtypes(include=["object", 'str']).columns: # avoid warning for multi execution
        df[col] = df[col].str.lower()
        print()
    print('-------------------',name,'-------------------')
    print(df.head(1))
    for col in df.select_dtypes(include=["object", 'str']).columns: # avoid warning for multi execution
        df[col] = df[col].str.lower()
        print()
    print('-------------------',name,'-------------------')
    print(df.head(1))

------------------- location -------------------
   locationid borough            zone
0           1     ewr  newark airport


------------------- location -------------------
   locationid borough            zone
0           1     ewr  newark airport


------------------- raw_2014 -------------------
          date/time     lat      lon    base
0  4/1/2014 0:11:00  40.769 -73.9549  b02512


------------------- raw_2014 -------------------
          date/time     lat      lon    base
0  4/1/2014 0:11:00  40.769 -73.9549  b02512



------------------- raw_2015 -------------------
  dispatching_base_num          pickup_date affiliated_base_num  locationid
0               b02617  2015-05-17 09:47:00              b02617         141



------------------- raw_2015 -------------------
  dispatching_base_num          pickup_date affiliated_base_num  locationid
0               b02617  2015-05-17 09:47:00              b02617         141

In [8]:
# os.makedirs('./c') # create directory then deactivate

In [9]:
location.to_csv("c/location.csv", index=False)

# Identify base in 2014

In [10]:
# raw_2014['base'].isin(raw_2015['dispatching_base_num']).value_counts()

On retrouve le nombre de lignes exact de raw_2014. Aucune base ne diffère des dispatching_base_num.
Pour s'en assurer, comparons les valeurs uniques.

In [11]:
b14 = set(raw_2014['base'].unique())
b15_dispatch = set(raw_2015['dispatching_base_num'].unique())
b15_licence = set(raw_2015['affiliated_base_num'].unique())
print(len(b14), len(b15_dispatch), len(b15_licence), len(b14 & b15_dispatch & b15_licence))

5 8 285 5

Base correspond à la référence du centre de dispatch. De 2014 à 2015, le nombre des centres de dispatch a été augmenté de 3.

# Identify location pickup

locationid est présent sur uber-raw-data-janjune-15 et taxi-zone-lookup. Nous pouvons les fusionner à partir de cette colonne.

# Merge raw_2015 and location

In [12]:
raw_2015 = raw_2015.merge(location[['locationid', "borough", "zone"]], left_on="locationid", right_on="locationid", how="left")
raw_2015.head(1)

,dispatching_base_num,pickup_date,affiliated_base_num,locationid,borough,zone
0,b02617,2015-05-17 09:47:00,b02617,141,manhattan,lenox hill west

# Treat missing values

La référence du taxi est inutile pour kmeans. On remplace par une étiquette explicite.

In [13]:
raw_2015['affiliated_base_num'] = raw_2015['affiliated_base_num'].fillna('unknown') # drop lines where values are missing. 
missing_values = raw_2015.isnull().sum()/raw_2015.shape[0]*100
print(missing_values)

dispatching_base_num    0.0
pickup_date             0.0
affiliated_base_num     0.0
locationid              0.0
borough                 0.0
zone                    0.0
dtype: float64

# Treat datetime

In [14]:
cols = [raw_2014["date/time"], raw_2015["pickup_date"]]

converted = [pd.to_datetime(c, format=f) for c, f in zip(cols, ("%m/%d/%Y %H:%M:%S", "%Y-%m-%d %H:%M:%S")) # zip to use c and f together
]

raw_2014["date/time"], raw_2015["pickup_date"] = converted
print(raw_2014["date/time"].dtypes) # datetime64[ns]
print(raw_2015["pickup_date"].dtypes)
print([c.dtype for c in converted])  # # M8[ns]

datetime64[us]
datetime64[us]
[dtype('<M8[us]'), dtype('<M8[us]')]

# Analyze one hour on one day

In [15]:
raw_2015.head(1)

,dispatching_base_num,pickup_date,affiliated_base_num,locationid,borough,zone
0,b02617,2015-05-17 09:47:00,b02617,141,manhattan,lenox hill west

In [16]:
raw_2014['date/time'].dtype

dtype('<M8[us]')

In [17]:
raw_2015['pickup_date'].dtype

dtype('<M8[us]')

Les bases b02617 et b02764 se superposent. Let's record bases and search for duplicated values.

In [18]:
pickup_14 = raw_2014
pickup_14.to_csv("c/2014.csv", index=False)

# Merge raw_2015 and location

In [19]:
# raw_2015 = raw_2015.merge(bases[["base", "lon", "lat"]], left_on="dispatching_base_num", right_on="base", how="left").drop(columns="base")
# print(raw_2015[["dispatching_base_num", "lon", "lat"]])
# print(raw_2015[["lon", "lat"]])

In [20]:
pickup = raw_2015
pickup.to_csv("c/2015.csv", index=False)

# Detect outlyers

On cherche seulement les points aberrants. Dans l'eau ou en dehors de l'état de new york.

# Create sample

In [21]:
begin = pd.Timestamp('2014-04-01 00:00:00')
end = begin + pd.Timedelta(hours=1)

s1 = pickup_14[(pickup_14['date/time'] >= begin) & (pickup_14['date/time'] < end)]
s1

                 date/time      lat      lon    base
0      2014-04-01 00:11:00  40.7690 -73.9549  b02512
1      2014-04-01 00:17:00  40.7267 -74.0345  b02512
2      2014-04-01 00:21:00  40.7316 -73.9873  b02512
3      2014-04-01 00:28:00  40.7588 -73.9776  b02512
4      2014-04-01 00:33:00  40.7594 -73.9722  b02512
...                    ...      ...      ...     ...
554608 2014-04-01 00:15:00  40.7430 -73.9518  b02764
554609 2014-04-01 00:21:00  40.7563 -73.9849  b02764
554610 2014-04-01 00:26:00  40.7636 -73.9756  b02764
554611 2014-04-01 00:42:00  40.7140 -74.0144  b02764
554612 2014-04-01 00:50:00  40.7395 -74.0019  b02764

[138 rows x 4 columns]

In [22]:
s1.to_csv("c/s1.csv", index=False)

In [23]:
begin = pd.Timestamp('2015-05-17 10:00:00')
end = begin + pd.Timedelta(hours=1)

t1 = pickup[(pickup['pickup_date'] >= begin) & (pickup['pickup_date'] < end)]
t1

,dispatching_base_num,pickup_date,affiliated_base_num,locationid,borough,zone
73,b02617,2015-05-17 10:00:00,b02617,229,manhattan,sutton place/turtle bay north
74,b02617,2015-05-17 10:00:00,b02617,141,manhattan,lenox hill west
75,b02617,2015-05-17 10:00:00,b02765,145,queens,long island city/hunters point
76,b02617,2015-05-17 10:00:00,b02774,255,brooklyn,williamsburg (north side)
77,b02617,2015-05-17 10:00:00,b02617,141,manhattan,lenox hill west
...,...,...,...,...,...,...
12488486,b02765,2015-05-17 10:58:00,b02765,231,manhattan,tribeca/civic center
12488487,b02765,2015-05-17 10:58:00,b02765,107,manhattan,gramercy
12488488,b02765,2015-05-17 10:59:00,b00448,173,queens,north corona
12488489,b02765,2015-05-17 10:59:00,b02512,133,brooklyn,kensington
12488490,b02765,2015-05-17 10:59:00,b02765,231,manhattan,tribeca/civic center

In [34]:
print(t1["borough"].nunique(), t1["zone"].nunique())

6 205

In [24]:
t1.to_csv("c/t1.csv", index=False)

# Search for duplicated values

In [31]:
# duplicated_values = bases[bases.duplicated(subset=["lat", "lon"], keep=False)]
# print(duplicated_values.sort_values(['base', "lat", "lon"]))

In [32]:
# with pd.option_context("display.precision", 15):
#     print(bases_median)

There are no duplicated values, only values very similar. Des points proches signalent justement une forte densité de pickups, donc une hot-zone. Les supprimer ferait perdre cette information et fausserait les clusters (KMeans comme DBSCAN).