In [1]:
import pandas as pd
import plotly.express as px
import plotly.graph_objects as go
import plotly.io as pio

In [ ]:
df_sample = pd.read_csv('data/sample.csv')

In [3]:
df_sample.head(1)

,dispatching_base_num,pickup_date,affiliated_base_num,locationid,borough,zone,lon,lat
0,b02512,2015-04-27 13:21:00,b02682,66,brooklyn,dumbo/vinegar hill,-73.9844,40.7473

In [7]:
df_sample["pickup_date"] = pd.to_datetime(df_sample["pickup_date"])
df_sample['month'] = df_sample["pickup_date"].dt.month
df_sample["hour"] = df_sample["pickup_date"].dt.hour
df_sample["dayofweek"] = df_sample["pickup_date"].dt.dayofweek
df_sample.head(1)

,dispatching_base_num,pickup_date,affiliated_base_num,locationid,borough,zone,lon,lat,month,hour,dayofweek
0,b02512,2015-04-27 13:21:00,b02682,66,brooklyn,dumbo/vinegar hill,-73.9844,40.7473,4,13,0

In [ ]:
# # Remove the "locationid" variable from your dataset.

# # On jette les colonnes inutiles
# useless_cols = ['locationid', 'pickup_date']

# print("Les colonnes suivantes vont être jetées : ", useless_cols)
# raw_2015 = raw_2015.drop(useless_cols, axis=1)
# print("...Terminé.")
# print(raw_2015.head())

# Normalize dataset

In [ ]:
# Création du pipeline pour les variables quantitatives
numeric_features = [6,7] # Positions des colonnes quantitatives dans X
numeric_transformer = Pipeline(steps=[
    ('scaler', StandardScaler()) # pour normaliser les variables
])

# Création du pipeline pour les variables catégorielles
categorical_features = ['pickup_date',	'affiliated_base_num',	'locationid	borough	zone',	'lon',	'lat'] # Positions des colonnes catégorielles dans X
categorical_transformer = Pipeline(
    steps=[
    ('encoder', OneHotEncoder(drop='first')) # on encode les catégories sous forme de colonnes comportant des 0 et des 1
    ])

# On combine les pipelines dans un ColumnTransformer
preprocessor = ColumnTransformer(
    transformers=[
        ('num', numeric_transformer, numeric_features),
        ('cat', categorical_transformer, categorical_features)
    ])

# Preprocessings sur le dataset
print("Preprocessing sur le train set...")
print(dataset.head())
X = preprocessor.fit_transform(dataset) # fit_transform !!
print('...Terminé.')
print(X[0:5, :])
print()