In [1]:
import pandas as pd
import quality_func

In [2]:
zone = quality_func.load_zone_data()

Set with labels : (564516, 4)

In [3]:
files = ["data/uber-trip-data/uber-raw-data-apr14.csv", "data/uber-trip-data/uber-raw-data-may14.csv", "data/uber-trip-data/uber-raw-data-jun14.csv", 'data/uber-trip-data/uber-raw-data-jul14.csv', 'data/uber-trip-data/uber-raw-data-aug14.csv', 'data/uber-trip-data/uber-raw-data-sep14.csv']

raw_2014 = quality_func.load_2014_data(files)

Set with labels : (4534327, 4)

In [4]:
raw_2015 = quality_func.load_2015_data('data/uber-trip-data/uber-raw-data-janjune-15.csv')

Set with labels : (14270479, 4)

# Explore dataset

In [5]:
dataframes_viz = [zone, raw_2014, raw_2015]
[print(f"Display of dataset: {display(df.head())}") for df in dataframes_viz]

          Date/Time      Lat      Lon    Base
0  4/1/2014 0:11:00  40.7690 -73.9549  B02512
1  4/1/2014 0:17:00  40.7267 -74.0345  B02512
2  4/1/2014 0:21:00  40.7316 -73.9873  B02512
3  4/1/2014 0:28:00  40.7588 -73.9776  B02512
4  4/1/2014 0:33:00  40.7594 -73.9722  B02512

Display of dataset: None

          Date/Time      Lat      Lon    Base
0  4/1/2014 0:11:00  40.7690 -73.9549  B02512
1  4/1/2014 0:17:00  40.7267 -74.0345  B02512
2  4/1/2014 0:21:00  40.7316 -73.9873  B02512
3  4/1/2014 0:28:00  40.7588 -73.9776  B02512
4  4/1/2014 0:33:00  40.7594 -73.9722  B02512

Display of dataset: None

  Dispatching_base_num          Pickup_date Affiliated_base_num  locationID
0               B02617  2015-05-17 09:47:00              B02617         141
1               B02617  2015-05-17 09:47:00              B02617          65
2               B02617  2015-05-17 09:47:00              B02617         100
3               B02617  2015-05-17 09:47:00              B02774          80
4               B02617  2015-05-17 09:47:00              B02617          90

Display of dataset: None

[None, None, None]

In [6]:
# Basic stats
dataframes = quality_func.dataframes_stats(zone, raw_2014, raw_2015)

-------------------Dataframe :  zone -------------------
Rows :  	 564516
Columns : 	 4

Basics statistics:
Percentage of missing values
zone :
Date/Time    0.0
Lat          0.0
Lon          0.0
Base         0.0
dtype: float64

-------------------Dataframe :  raw_2014 -------------------
Rows :  	 4534327
Columns : 	 4

Basics statistics:
Percentage of missing values
raw_2014 :
Date/Time    0.0
Lat          0.0
Lon          0.0
Base         0.0
dtype: float64

-------------------Dataframe :  raw_2015 -------------------
Rows :  	 14270479
Columns : 	 4

Basics statistics:
Percentage of missing values
raw_2015 :
Dispatching_base_num    0.000000
Pickup_date             0.000000
Affiliated_base_num     1.136577
locationID              0.000000
dtype: float64
Done...

In [7]:
type(dataframes)

dict

In [8]:
missing_values = quality_func.observe_missing_values(dataframes)

------------------- zone -------------------
          Date/Time     Lat      Lon    Base
0  4/1/2014 0:11:00  40.769 -73.9549  b02512
------------------- raw_2014 -------------------
          Date/Time     Lat      Lon    Base
0  4/1/2014 0:11:00  40.769 -73.9549  b02512
------------------- raw_2015 -------------------
  Dispatching_base_num          Pickup_date Affiliated_base_num  locationID
0               b02617  2015-05-17 09:47:00              b02617         141

# Nettoyage des données pour préparer l'analyse exploratoire

In [9]:
type(zone)

pandas.core.frame.DataFrame

In [10]:
print("Zone dataset:")
print(zone.shape)
display(zone.head())

Zone dataset:
(564516, 4)

          Date/Time      Lat      Lon    Base
0  4/1/2014 0:11:00  40.7690 -73.9549  b02512
1  4/1/2014 0:17:00  40.7267 -74.0345  b02512
2  4/1/2014 0:21:00  40.7316 -73.9873  b02512
3  4/1/2014 0:28:00  40.7588 -73.9776  b02512
4  4/1/2014 0:33:00  40.7594 -73.9722  b02512

In [11]:
print("2014 dataset:")
print(zone.shape)
display(raw_2014.head())

2014 dataset:
(564516, 4)

          Date/Time      Lat      Lon    Base
0  4/1/2014 0:11:00  40.7690 -73.9549  b02512
1  4/1/2014 0:17:00  40.7267 -74.0345  b02512
2  4/1/2014 0:21:00  40.7316 -73.9873  b02512
3  4/1/2014 0:28:00  40.7588 -73.9776  b02512
4  4/1/2014 0:33:00  40.7594 -73.9722  b02512

In [12]:
zone["Base"].value_counts()

Base
b02682    227808
b02598    183263
b02617    108001
b02512     35536
b02764      9908
Name: count, dtype: int64

In [13]:
print("2015 dataset:")
print(raw_2015.shape)
display(raw_2015.head())

2015 dataset:
(14270479, 4)

  Dispatching_base_num          Pickup_date Affiliated_base_num  locationID
0               b02617  2015-05-17 09:47:00              b02617         141
1               b02617  2015-05-17 09:47:00              b02617          65
2               b02617  2015-05-17 09:47:00              b02617         100
3               b02617  2015-05-17 09:47:00              b02774          80
4               b02617  2015-05-17 09:47:00              b02617          90

In [14]:
raw_2015.value_counts()

Dispatching_base_num  Pickup_date          Affiliated_base_num  locationID
b02682                2015-05-27 20:30:00  b02682               161           10
                      2015-06-18 21:09:00  b02682               161            9
b02764                2015-03-03 22:11:00  b02764               230            9
b02682                2015-05-17 01:18:00  b02682               79             9
                      2015-05-17 00:46:00  b02682               79             9
                                                                              ..
                      2015-03-14 10:41:00  b02818               142            1
                                                                163            1
                      2015-03-14 10:42:00  b02682               107            1
                                                                113            1
b02836                2015-06-30 23:29:00  b02836               144            1
Name: count, Length: 13211552, dtype: int64

In [15]:
begin = pd.Timestamp('2014-04-01 00:00:00')
end = begin + pd.Timedelta(hours=1)

t1 = raw_2014[(raw_2014['date/time'] >= begin) & (raw_2014['date/time'] < end)]

KeyError: 'date/time'

In [ ]:
bases_median = t1.groupby('base')[['lat', 'lon']].median().reset_index()

In [ ]:
fig = px.scatter_map(bases_median, lat="lat", lon="lon", color="base", zoom=10, map_style="open-street-map")
fig.show()

In [ ]:
bases = raw_2014.groupby('base')[['lat', 'lon']].median().reset_index()